version: '3.7'
services:
  
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
      
    restart: always
    
    container_name: postgres12
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 53cret
      POSTGRES_DB: postgres